---
name: evopt
version: "sha-c286179"
slug: evopt
description: Optimierer für Ladevorgänge (evopt) als Home Assistant Add-on
url: https://github.com/andig/evopt
arch: 
  - amd64
startup: application
boot: auto
legacy: true
stage: experimental
init: false
image: litithio/evopt
ports:
  7050/tcp: 7050
ports_description:
  7050/tcp: "evopt HTTP API"
map:
  - type: addon_config
    read_only: false
  - type: homeassistant_config
    read_only: false
ingress: true
host_network: true
